name: My First Workflow

on: push

jobs:
  ascii_jobs:
        runs-on: ubuntu_latest
        steps:
            -  name: Checkout repo
               uses: action/checkout@v4

            - name: Install Cowsay program
              run: sudo apt -get install cowsay -y 

            - name: execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWN" >> dragon.txt

            - name: test file execute
              run: grep -i "dragon" dragon.txt

            - name: Read file
              run: cat Readme.md

            - name: list Repo files
              run: ls -ltra